### ISSUE TITLE
[BUG] :updating the broken links in docs

### ISSUE THREAD

**Issue by abhijeet78880** [osbc2022/interactive-eloquent-js-website#10]
### ✏️ Describe the bug

the links are broken and do not matches with this repo.
so fix all the links and guide docs acc to this repo.

### 📸 Screenshots

![Screenshot from 2022-10-31 20-35-38](https://user-images.githubusercontent.com/84617107/199041890-7ced157e-c9c2-4072-a708-3add3e6123e7.png)

**Comment by osbc2022** [comment]
go for it @abhijeet78880
