### ISSUE TITLE
Create the menu

### ISSUE THREAD

**Issue by osbc2022** [osbc2022/interactive-eloquent-js-website#3]
Todo :- 
- [ ] create a menu with 3 accordion , it should open on click
![image](https://user-images.githubusercontent.com/115569958/199019259-3ecbd454-f5ef-417a-b103-2779bea861ea.png)

- [ ] it should show all the chapter on click 
![image](https://user-images.githubusercontent.com/115569958/199019810-1b92da08-3626-4a44-a9bc-7c9196395822.png)

**Comment by amitanshusahu** [comment]
i can work on this
