### ISSUE TITLE
[FEAT] : Redesigining the nav bar

### ISSUE THREAD

**Issue by amitanshusahu** [osbc2022/interactive-eloquent-js-website#6]
### ✏️ Description

the nav bar is very basic the menu button is not required 

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/83657737/199023790-781cf1da-617d-4e2c-83a2-4898b669e20c.png)

**Comment by osbc2022** [comment]
you are right , go for it :star:  , i think you should be a member of the club..

**Comment by abhijeet78880** [comment]
assign me this task..
